const file = document.getElementById(mapInput)
console.log("file " + String(file))
const ppgs = document.getElementById(pixelsPerSquare)
console.log("ppgs " + String(ppgs))
const overlapMargin = document.getElementById(overlapMargin)
console.log("overlayMargin" + String(overlayMargin))
const pageMargin = document.getElementById(pageMargin)
console.log("pageMargin" + String(pageMargin))
const canvas = document.getElementById(mapCanvas)
console.log("canvas" + String(canvas))
const canvasContext = canvas.getContext('2d')
console.log("canvasContext" + String(canvasContext))
